### ISSUE TITLE
Using themeserviceoverride with an own tokenizer causes runtime-errors

### ISSUE THREAD

**Issue by mep-bsw** [CodinGame/monaco-vscode-api#408]
![grafik](https://github.com/CodinGame/monaco-vscode-api/assets/90831097/f0997300-a8dc-4f83-aef8-068d1cbb36cb)
i think this happens if theres is no matching theme-data associated with the returned tokens from my own tokenizer.

this error only comes up when using themeserviceovveride together with monaco.languages.setTokensprovider.

Im rather new to this, so please feel free to educate me on this, if im wrong.

**Comment by CGNonofr** [comment]
Your problem is that the `TokenizationSupportAdapter` takes the theme service as parameter and directly infer it's the standalone (monaco) implementation, which is not when using the theme service override

Note that it seems to be an issue only for the `TokensProvider`, not the `EncodedTokensProvider`

Out of curiosity, what is the tokenizer you're trying to implement?

**Comment by mep-bsw** [comment]
im implementing my own tokenizer for a very obscure and specific dsl. thanks for the info ^^

**Comment by mep-bsw** [comment]
so in order for my tokens to receive coloring, i must register a theme with customTokenColors, if i wish to have a vscode-theme?

**Comment by CGNonofr** [comment]
I'm not sure I will be able to help you on this specific topic

But If you're able to use a textmate grammar instead of implementing the tokenizer by hand, it would probably be simpler
