### ISSUE TITLE
Searching special RegEx characters does not return result with RegEx enabled

### ISSUE THREAD

**Issue by bosunski** [CodinGame/monaco-vscode-api#462]
When special RegEx characters (likes of `\ + * ? [ ^ ] $ ( ) { } = ! < > | : -`) are entered in the search input and RegEx mode is enabled, the search keeps loading without return. These can be reproduced in the [Online Demo](https://monaco-vscode-api.netlify.app) too.

<img width="487" alt="Screenshot 2024-07-11 at 17 47 05" src="https://github.com/CodinGame/monaco-vscode-api/assets/15146515/9a97c598-41cd-4d24-a4c1-1e5b3d6524cb">

Meanwhile, on Local VSCode or [VSCode.dev](https://vscode.dev), you will get an error, which is expected.

<img width="332" alt="Screenshot 2024-07-11 at 17 46 45" src="https://github.com/CodinGame/monaco-vscode-api/assets/15146515/df4bfbf2-9a3d-4d88-9f26-9ba3b38d227a">

**Comment by CGNonofr** [comment]
That's because the search in VSCode can only operate:
- Via the HTMLFileSystemProvider
- On a remote host, via the Server Extension host

In the demo, we use a virtual client filesystem and there is no built-in way to search in it, so the demo implements a [basic search](https://github.com/CodinGame/monaco-vscode-api/blob/main/demo/src/features/search.ts) that is probably not handling edge cases very well

If you enable the html filesystem provider and open a local directory, do you confirm the searching works well?

**Comment by bosunski** [comment]
The same issue happens when using HTML filesystem. I also think this doesn't have something to do with the filesystem provider because, when this happens, the [`provideTextSearchResults`](https://github.com/CodinGame/monaco-vscode-api/blob/e8963a3e14234f5960ca9e9d09ecc390255ed3f5/demo/src/features/search.ts#L25) exposed by the provider is not even called. So, I think this might be something else.

**Comment by bosunski** [comment]
Opening the search in the editor, did reveal an error that would have been seen in the UI (as in the image in the issue description). This also _seems_ to be before the provider is called.

<img width="2056" alt="Screenshot 2024-07-11 at 21 35 46" src="https://github.com/user-attachments/assets/99506c39-f74d-4df7-b5ab-4a598a2e31f4">

**Comment by CGNonofr** [comment]
Ok It looks like you're right! I've found the issue, fix is coming soon, thanks for the report!
