### ISSUE TITLE
Did typescript language features use core js?

### ISSUE THREAD

**Issue by ZWQ652** [CodinGame/monaco-vscode-api#501]
![image](https://github.com/user-attachments/assets/34b6a1a0-cf21-43f5-8bb0-2c51a6fdc27b)
Did typescript language features use core js? 
I noticed that it was not used in the dependency package, but this error was reported in the end.

**Comment by CGNonofr** [comment]
The error probably comes from your bundler configuration that tries to polyfill stuff using code-js

**Comment by ZWQ652** [comment]
> The error probably comes from your bundler configuration that tries to polyfill stuff using code-js这个错误可能是你的打包工具配置试图使用code-js打补丁导致的

How should I do it? Default packaging configuration using the development mode of vuecli

**Comment by CGNonofr** [comment]
The problem is it probably tries to transform extension code, because it's imported with the `new URL(<...>, import.meta.url)` syntax. This is an issue with webpack for instance where adding `dependency: { not: ['url'] },` on the babel loader is required to prevent it from trying to transform VSCode extension codes

**Comment by ZWQ652** [comment]
ok, 
![image](https://github.com/user-attachments/assets/ce26a148-40d9-4124-8362-b858dd85b53e)
