### ISSUE TITLE
Tree shaking

### ISSUE THREAD

**Issue by char0n** [CodinGame/monaco-vscode-api#55]
No sure if it's relevant, but I did couple of tests with webpack@5 and this library.

When I use the following code, and bundle it using webpack, I'm ending up with quite huge bundle sizes. It looks like the whole `vscode` gets sucked in. Has this library been tested for tree-shaking using webpack@5?

```js
import { version } from 'vscode';

console.dir(version);
```

**Comment by CGNonofr** [comment]
Oh I missed that issue, sorry for that

Not the whole vscode gets sucked in, only the parts required for monaco-languageclient AND simple parts (like version)

What do you mean by `been tested for tree-shaking using webpack@5`?

**Comment by char0n** [comment]
> Oh I missed that issue, sorry for that

No worries.

> Not the whole vscode gets sucked in, only the parts required for monaco-languageclient AND simple parts (like version) that are not already in monaco-editor.

Well that is kind of my point. If I just need version, is it necessary to pull in other code as well? I would imagine that whatever I import from this library, only parts that are used by my import will get pulled in. 

> What do you mean by been tested for tree-shaking using webpack@5?

I've seen #2 and #3, so I guess there's been testing. So never mind my question.

**Comment by CGNonofr** [comment]
I see no reason for webpack not being able to treeshake everything else out if you only use the version (even if it's a very strange need?)

Treeshaking was a challenge here, because I wanted to reuse the code already in monaco as much as possible, but the monaco build process treeshaking is very aggressive so a lot of things got removed, that's why I needed to [polyfill](https://github.com/CodinGame/monaco-vscode-api/blob/main/src/polyfill.ts) what was already existing in monaco and to have a [very complex rollup config](https://github.com/CodinGame/monaco-vscode-api/blob/main/rollup/rollup.config.ts) to evaluate what is already existing in monaco and what's not

Rollup treeshaking is not perfect, is even has some bug that makes it keep completely unused code, but I think we'll still near an optimal solution

**Comment by char0n** [comment]
> I see no reason for webpack not being able to treeshake everything else out if you only use the version (even if it's a very strange need?)

I didn't investigate further, I've just run a simple experiment and that was the result.

> Treeshaking was a challenge here, because I wanted to reuse the code already in monaco as much as possible, but the monaco build process treeshaking is very aggressive so a lot of things got removed, that's why I needed to [polyfill](https://github.com/CodinGame/monaco-vscode-api/blob/main/src/polyfill.ts) what was already existing in monaco and to have a [very complex rollup config](https://github.com/CodinGame/monaco-vscode-api/blob/main/rollup/rollup.config.ts) to evaluate what is already existing in monaco and what's not
>Rollup treeshaking is not perfect, is even has some bug that makes it keep completely unused code, but I think we'll still near an optimal solution

Sure, I've just raised an issue to make sure you're aware of this. It's not a big issue or a blocker for me. Thanks for all the work you put into this lib.
