### ISSUE TITLE
Demo is broken with latest version (1.69.21)

### ISSUE THREAD

**Issue by kaisalmen** [CodinGame/monaco-vscode-api#68]
Hi @CGNonofr 

I updated the demo (branch: https://github.com/CodinGame/monaco-vscode-api/tree/kaisalmen/demo-update) to the latest release and there is problem:
![image](https://user-images.githubusercontent.com/21079138/221567726-7841ca93-cecb-45a3-a86d-b29b370880fa.png)

Switching to `1.69.20` it is still working. I see this error, though:
![image](https://user-images.githubusercontent.com/21079138/221569237-dcb5c513-c0a0-4cea-9c51-d156791aa4ec.png)

Are you aware of this already?

**Comment by CGNonofr** [comment]
Hello!

The demo isn't updated automatically indeed and we should probably use a workspace npm here?

That's very surprising that the 1.69.21 breaks anything since it's just a very small feature and a dev lib update, I'll have a look :shrug: 

> I see this error, though:

This log message is not new, if was just changed/improve recently. Unfortunately there's nothing to do except merging https://github.com/microsoft/vscode/pull/156120

**Comment by kaisalmen** [comment]
> The demo isn't updated automatically indeed and we should probably use a workspace npm here?

Should I introduce it with a PR?

**Comment by CGNonofr** [comment]
Sure! feel free to make any improvement here if you think it will be better based on your experience with monaco-languageclient

**Comment by kaisalmen** [comment]
I have created a draft PR: https://github.com/CodinGame/monaco-vscode-api/pull/69

**Comment by CGNonofr** [comment]
The ProductQualityContext error was due the the polyfill being loaded too late, it was a race condition not happening in my tests elsewhere.

It's fixed in https://github.com/CodinGame/monaco-vscode-api/pull/70 in 2 differents ways, along with another bug regarding modals.
